In [1]:
import pandas as pd
dir = "../database/database.xlsx"

In [2]:
df_datasiswa = pd.read_excel(dir, sheet_name="datasiswa")

#drop column nama pada sheet intro_ai, karena akan disambungkan dengan dataframe utama
df1 = pd.read_excel(dir, sheet_name="intro_ai")
df1 = df1.drop(['nama'], axis=1)

#drop column nama pada sheet python, karena akan disambungkan dengan dataframe utama
df2 = pd.read_excel(dir, sheet_name="python")
df2 = df2.drop(['nama'], axis=1)

#penggabungan antar dataframe menjadi 1 dataframe utama
df = pd.concat([df_datasiswa, df1, df2], axis=1)

,nama,id_msib,nohp,email,intro_1,intro_2,intro_3,intro_4,intro_5,absen_intro_1,absen_intro_2,absen_intro_3,absen_intro_4,absen_intro_5,jumlah_absen_intro,posttest_intro_ai,final_intro_ai,alphabet_intro_ai
0,kosong,0,0,aa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,E
1,ani saputri,4845859,83863024527,2010631030003@student.unsika.ac.id,90.0,100.0,90.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,82.2,A
2,anisa sekar pradita,4522447,8886640365,anisaasekar2018@students.unnes.ac.id,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,87.4,A
3,arya al rian yayat,4458277,83132703440,aryaalrianyayat10@gmail.com,90.0,100.0,95.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,40.0,74.5,B
4,daffa ammar pratama,4718941,85710467958,daffa.pratama@mhs.unsoed.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,91.7,A
5,elyza dewi fortuna,5094517,85741449773,elyzadefzz@gmail.com,90.0,100.0,95.0,100.0,85.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,90.2,A
6,fauzan nur cholis,5672734,85713887466,kholisfauzan34@gmail.com,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,83.7,A
7,haidariyad iskandar,5307156,87709046365,111202013185@mhs.dinus.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.7,A
8,hamidatul ulfa,4446875,85238630929,hamidatululfa28@gmail.com,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E
9,ingwie bintang pramudyas,5473046,82246716417,ipram45@gmail.com,90.0,100.0,90.0,100.0,85.0,1.0,1.0,1.0,0.0,1.0,4.0,60.0,75.9,B
10,muhamad akhirul sidik,5549226,82127456614,20200910055@uniku.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.7,A
11,nadiva naifa najla,4425468,87824398505,divaanaifaa@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,87.4,A
12,noor syafa'ah kusuma putri,4423585,85290714959,noorsya16@gmail.com,90.0,100.0,90.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,86.2,A
13,nuansa bening,5498242,85156798946,nuansa1329@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.4,A
14,raymundus erik chandra yunanta,4489640,89643662622,20530035.raymundus@sinus.ac.id,90.0,100.0,95.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,94.5,A
15,risdianti,5137392,82251589036,risdianti01@gmail.com,90.0,100.0,95.0,100.0,85.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,82.2,A
16,rizki arief dehanudin,5091754,87708264025,riskyarief2012@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.4,A
17,windi puspitasari,5651205,85691023963,puspitasariwindi9@gmail.com,90.0,100.0,95.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,86.5,A
18,yulianti,4859934,83162251403,yulianti@std.unissula.ac.id,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,91.4,A
19,dummy 1,3000001,82225700071,aa@com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E
20,dummy 2,3000002,82225700071,aa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E