In [4]:
import pandas as pd
dir = "../database/database.xlsx"

In [5]:
df_datasiswa = pd.read_excel(dir, sheet_name="datasiswa")

#drop column nama pada sheet intro_ai, karena akan disambungkan dengan dataframe utama
df1 = pd.read_excel(dir, sheet_name="intro_ai")
df1 = df1.drop(['nama'], axis=1)

#drop column nama pada sheet python, karena akan disambungkan dengan dataframe utama
df2 = pd.read_excel(dir, sheet_name="python")
df2 = df2.drop(['nama'], axis=1)

#penggabungan antar dataframe menjadi 1 dataframe utama
df = pd.concat([df_datasiswa, df1, df2], axis=1)

df

,nama,id_msib,nohp,email,intro_1,intro_2,intro_3,intro_4,intro_5,absen_intro_1,...,absen_python_3,absen_python_4,asben_python_5,absen_python_6,absen_python_7,absen_python_8,jml_absen_python,posttest_python,final_python,alphabet_python
0,kosong,0,0,aa,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E
1,Ani Saputri,4845859,83863024527,2010631030003@student.unsika.ac.id,90.0,100.0,90.0,100.0,90.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,60.0,82.13,A
2,Anisa Sekar Pradita,4522447,8886640365,anisaasekar2018@students.unnes.ac.id,100.0,100.0,90.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,40.0,70.94,B
3,Arya Al Rian Yayat,4458277,83132703440,aryaalrianyayat10@gmail.com,90.0,100.0,95.0,100.0,90.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,60.0,80.81,A
4,Daffa Ammar Pratama,4718941,85710467958,daffa.pratama@mhs.unsoed.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,60.0,82.13,A
5,Elyza Dewi Fortuna,5094517,85741449773,elyzadefzz@gmail.com,90.0,100.0,95.0,100.0,85.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,7.0,60.0,78.56,B
6,Fauzan Nur Cholis,5672734,85713887466,kholisfauzan34@gmail.com,100.0,100.0,95.0,100.0,100.0,1.0,...,1.0,1.0,1.0,0.0,1.0,1.0,7.0,60.0,78.19,B
7,Haidariyad Iskandar,5307156,87709046365,111202013185@mhs.dinus.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,100.0,98.69,A
8,Hamidatul Ulfa,4446875,85238630929,hamidatululfa28@gmail.com,NaN,NaN,NaN,NaN,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,E
9,Ingwie Bintang Pramudyas,5473046,82246716417,ipram45@gmail.com,90.0,100.0,90.0,100.0,85.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,7.0,40.0,45.81,D
10,Muhamad Akhirul Sidik,5549226,82127456614,20200910055@uniku.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,80.0,91.25,A
11,Nadiva Naifa Najla,4425468,87824398505,divaanaifaa@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,100.0,99.25,A
12,Noor Syafa'ah Kusuma Putri,4423585,85290714959,noorsya16@gmail.com,90.0,100.0,90.0,100.0,90.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,80.0,91.63,A
13,Nuansa Bening,5498242,85156798946,nuansa1329@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,100.0,99.63,A
14,Raymundus Erik Chandra Yunanta,4489640,89643662622,20530035.raymundus@sinus.ac.id,90.0,100.0,95.0,100.0,90.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,80.0,91.44,A
15,Risdianti,5137392,82251589036,risdianti01@gmail.com,90.0,100.0,95.0,100.0,85.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,80.0,90.31,A
16,Rizki Arief Dehanudin,5091754,87708264025,riskyarief2012@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,60.0,84.00,A
17,Windi Puspitasari,5651205,85691023963,puspitasariwindi9@gmail.com,90.0,100.0,95.0,100.0,90.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,60.0,80.81,A
18,Yulianti,4859934,83162251403,yulianti@std.unissula.ac.id,100.0,100.0,90.0,100.0,100.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,8.0,60.0,80.06,A
19,Dummy 1,3000001,82225700071,aa@com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,E
20,Dummy 2,3000002,82225700071,aa,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,E