In [1]:
import pandas as pd
dir = "../database/database.xlsx"

In [2]:
df_datasiswa = pd.read_excel(dir, sheet_name="datasiswa")
df1 = pd.read_excel(dir, sheet_name="intro_ai")
df1 = df1.drop(['nama'], axis=1)

df = pd.concat([df_datasiswa, df1], axis=1)

df['nama'] = df['nama'].str.lower()

df

,nama,id_msib,nohp,email,intro_1,intro_2,intro_3,intro_4,intro_5,absen_intro_1,absen_intro_2,absen_intro_3,absen_intro_4,asben_intro_5,jumlahl_absen_intro,posttest_intro_ai,final_intro_ai,alphabet_intro_ai
0,kosong,9999,9999,alpha@google.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,E
1,ani saputri,4845859,83863024527,2010631030003@student.unsika.ac.id,90.0,100.0,90.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,82.2,A
2,anisa sekar pradita,4522447,8886640365,anisaasekar2018@students.unnes.ac.id,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,87.4,A
3,arya al rian yayat,4458277,83132703440,aryaalrianyayat10@gmail.com,90.0,100.0,95.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,40.0,74.5,B
4,daffa ammar pratama,4718941,85710467958,daffa.pratama@mhs.unsoed.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,91.7,A
5,elyza dewi fortuna,5094517,85741449773,elyzadefzz@gmail.com,90.0,100.0,95.0,100.0,85.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,90.2,A
6,fauzan nur cholis,5672734,85713887466,kholisfauzan34@gmail.com,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,83.7,A
7,haidariyad iskandar,5307156,87709046365,111202013185@mhs.dinus.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.7,A
8,hamidatul ulfa,4446875,85238630929,hamidatululfa28@gmail.com,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E
9,ingwie bintang pramudyas,5473046,82246716417,ipram45@gmail.com,90.0,100.0,90.0,100.0,85.0,1.0,1.0,1.0,0.0,1.0,4.0,60.0,75.9,B
10,muhamad akhirul sidik,5549226,82127456614,20200910055@uniku.ac.id,100.0,100.0,95.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.7,A
11,nadiva naifa najla,4425468,87824398505,divaanaifaa@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,87.4,A
12,noor syafa'ah kusuma putri,4423585,85290714959,noorsya16@gmail.com,90.0,100.0,90.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,86.2,A
13,nuansa bening,5498242,85156798946,nuansa1329@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.4,A
14,raymundus erik chandra yunanta,4489640,89643662622,20530035.raymundus@sinus.ac.id,90.0,100.0,95.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,94.5,A
15,risdianti,5137392,82251589036,risdianti01@gmail.com,90.0,100.0,95.0,100.0,85.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,82.2,A
16,rizki arief dehanudin,5091754,87708264025,riskyarief2012@gmail.com,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.4,A
17,windi puspitasari,5651205,85691023963,puspitasariwindi9@gmail.com,90.0,100.0,95.0,100.0,90.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,86.5,A
18,yulianti,4859934,83162251403,yulianti@std.unissula.ac.id,100.0,100.0,90.0,100.0,100.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,91.4,A
19,dummy 1,3000001,82225700071,aa@com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E
20,dummy 2,3000002,82225700071,aa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E

In [3]:
df_avg_tugas_intro_ai = df.iloc[:,4:9].sum(axis=1)

df_avg_tugas_intro_ai = df_avg_tugas_intro_ai / 5
df_avg_tugas_intro_ai

0      0.0
1     94.0
2     98.0
3     95.0
4     99.0
5     94.0
6     99.0
7     99.0
8      0.0
9     93.0
10    99.0
11    98.0
12    94.0
13    98.0
14    95.0
15    94.0
16    98.0
17    95.0
18    98.0
19     0.0
20     0.0
dtype: float64

In [4]:
df.insert(9, 'avg_tugas_intro', df_avg_tugas_intro_ai)

df

,nama,id_msib,nohp,email,intro_1,intro_2,intro_3,intro_4,intro_5,avg_tugas_intro,absen_intro_1,absen_intro_2,absen_intro_3,absen_intro_4,asben_intro_5,jumlahl_absen_intro,posttest_intro_ai,final_intro_ai,alphabet_intro_ai
0,kosong,9999,9999,alpha@google.com,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,E
1,ani saputri,4845859,83863024527,2010631030003@student.unsika.ac.id,90.0,100.0,90.0,100.0,90.0,94.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,82.2,A
2,anisa sekar pradita,4522447,8886640365,anisaasekar2018@students.unnes.ac.id,100.0,100.0,90.0,100.0,100.0,98.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,87.4,A
3,arya al rian yayat,4458277,83132703440,aryaalrianyayat10@gmail.com,90.0,100.0,95.0,100.0,90.0,95.0,1.0,1.0,1.0,1.0,1.0,5.0,40.0,74.5,B
4,daffa ammar pratama,4718941,85710467958,daffa.pratama@mhs.unsoed.ac.id,100.0,100.0,95.0,100.0,100.0,99.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,91.7,A
5,elyza dewi fortuna,5094517,85741449773,elyzadefzz@gmail.com,90.0,100.0,95.0,100.0,85.0,94.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,90.2,A
6,fauzan nur cholis,5672734,85713887466,kholisfauzan34@gmail.com,100.0,100.0,95.0,100.0,100.0,99.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,83.7,A
7,haidariyad iskandar,5307156,87709046365,111202013185@mhs.dinus.ac.id,100.0,100.0,95.0,100.0,100.0,99.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.7,A
8,hamidatul ulfa,4446875,85238630929,hamidatululfa28@gmail.com,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E
9,ingwie bintang pramudyas,5473046,82246716417,ipram45@gmail.com,90.0,100.0,90.0,100.0,85.0,93.0,1.0,1.0,1.0,0.0,1.0,4.0,60.0,75.9,B
10,muhamad akhirul sidik,5549226,82127456614,20200910055@uniku.ac.id,100.0,100.0,95.0,100.0,100.0,99.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.7,A
11,nadiva naifa najla,4425468,87824398505,divaanaifaa@gmail.com,100.0,100.0,90.0,100.0,100.0,98.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,87.4,A
12,noor syafa'ah kusuma putri,4423585,85290714959,noorsya16@gmail.com,90.0,100.0,90.0,100.0,90.0,94.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,86.2,A
13,nuansa bening,5498242,85156798946,nuansa1329@gmail.com,100.0,100.0,90.0,100.0,100.0,98.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.4,A
14,raymundus erik chandra yunanta,4489640,89643662622,20530035.raymundus@sinus.ac.id,90.0,100.0,95.0,100.0,90.0,95.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,94.5,A
15,risdianti,5137392,82251589036,risdianti01@gmail.com,90.0,100.0,95.0,100.0,85.0,94.0,1.0,1.0,1.0,1.0,1.0,5.0,60.0,82.2,A
16,rizki arief dehanudin,5091754,87708264025,riskyarief2012@gmail.com,100.0,100.0,90.0,100.0,100.0,98.0,1.0,1.0,1.0,1.0,1.0,5.0,90.0,95.4,A
17,windi puspitasari,5651205,85691023963,puspitasariwindi9@gmail.com,90.0,100.0,95.0,100.0,90.0,95.0,1.0,1.0,1.0,1.0,1.0,5.0,70.0,86.5,A
18,yulianti,4859934,83162251403,yulianti@std.unissula.ac.id,100.0,100.0,90.0,100.0,100.0,98.0,1.0,1.0,1.0,1.0,1.0,5.0,80.0,91.4,A
19,dummy 1,3000001,82225700071,aa@com,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E
20,dummy 2,3000002,82225700071,aa,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E

In [5]:
#wadah untuk inputan
nama = input("nama : ")

data = []

data.append(str(nama).lower().strip())

data

nama :  daffa ammar pratama

['daffa ammar pratama']

In [6]:
for x in df.index:
    A = df['nama'][x]
        

    #memvalidasi apakah nama, id_msib, univ, prodi, nohp sesuai atau tidak
    if (data[0] == A):
        df_tugas_intro = df.iloc[x, 4:10]
        df_tugas_intro = pd.to_numeric(df_tugas_intro)
        print(df_tugas_intro)

intro_1            100.0
intro_2            100.0
intro_3             95.0
intro_4            100.0
intro_5            100.0
avg_tugas_intro     99.0
Name: 4, dtype: float64

In [8]:
df_tugas_intro = df.iloc[3, 4:10]
df_tugas_intro

intro_1             90.0
intro_2            100.0
intro_3             95.0
intro_4            100.0
intro_5             90.0
avg_tugas_intro     95.0
Name: 3, dtype: object

In [11]:
type(df_tugas_intro)

pandas.core.series.Series

In [13]:
df_tugas_intro = df_tugas_intro.rename({"intro_1": "Tugas 1", "intro_2": "Tugas 2", "intro_3": "Tugas 3", 
                       "intro_4": "Tugas 4", "intro_5": "Tugas 5", "avg_tugas_intro": "Rata-rata Tugas"})
df_tugas_intro

Tugas 1             90.0
Tugas 2            100.0
Tugas 3             95.0
Tugas 4            100.0
Tugas 5             90.0
Rata-rata Tugas     95.0
Name: 3, dtype: object

In [23]:
dir2 = "../database/informasi_kelas.xlsx"

df_kelas = pd.read_excel(dir2, sheet_name="datakelas")

apollo_banyak_tugas_intro_ai = df_kelas.iloc[0, 1]
apollo_banyak_tugas_intro_ai

5.0